image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'python3 -m venv --system-site-packages ./venv && source ./venv/bin/activate'
    command: 'pip install --upgrade pip && pip install --upgrade tensorflow'
